# Generated by Django 4.2 on 2025-01-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kouryakuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category1',
            new_name='title',
        ),
    ]
