# Generated by Django 4.2 on 2025-01-30 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kouryakuapp', '0002_rename_category1_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kouryakuapp.kouryakupost', verbose_name='対象記事'),
        ),
    ]
