# Generated by Django 4.2 on 2025-01-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kouryakuapp', '0003_alter_comment_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(verbose_name='アップデート情報')),
                ('info_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日')),
            ],
        ),
    ]
